### ISSUE TITLE
cluster-api provider

### ISSUE THREAD

**Issue by siredmar** [linode/provider-linode#22]
Hi!

I'm pretty sure this repo is the absolute wrong place to place this issue, but i don't know any better place. So please forgive me :)

It would be really nice if there was an Linode cluster-api (CAPI) provider! 
It is pretty nice, that the crossplane provider exists to spin up Instances and stuff, but to be able to create a self managed kubernetes cluster one might use CAPI. 

Is this something on the backlog of Linode?

**Comment by siredmar** [comment]
btw, i found this: https://github.com/asauber/cluster-api-provider-linode
This could do as a starting point.

**Comment by srust** [comment]
Hi @siredmar appreciate the request!

This is something we have heard a lot and have a lot of interest in providing externally. So definitely stay tuned here.

Out of curiosity, are there any particular requirements you are looking for for the self managed cluster? Versions, capabilities, distros?

Thanks!

**Comment by siredmar** [comment]
Hi @srust!

well, my requirements are pretty basic: kubeadm bootstrap, kubeadm control-plane and a bunch of linode resources like instances and a nodebalancer. machinedeployments should be scalable. 
Linode instances should form some machines resources referenced by kubeadmincontrolplane and machinedeployment resources. 
As for versions I think it should be easily integrated whatever release kubernetes does. it downloads the binaries in specific versions with version dependent configurations.

Is the CAPI provider something that can be put in any time frame ore just a brief idea of supporting this some time in the future?

**Comment by srust** [comment]
In progress - not ready for consumption yet, but signification progress is currently being made:

https://github.com/linode/cluster-api-provider-linode
