### ISSUE TITLE
Missing access key id on objectstorage key

### ISSUE THREAD

**Issue by mwienk** [linode/provider-linode#5]
I can succesfully create a Key object in Linode, but when I try to use the credentials in my application I can only see the secret key in the k8s secret. As I also need to use an access key id for s3 connections, so I'm wondering how I would be able to retrieve it. It does seem to be available in the status of the managed resource.

Any help would be greatly appreciated.

**Comment by eljohnson92** [comment]
@mwienk Thanks for reporting this issue, I've opened up a PR to look to fix this and will hopefully get a release cut with this fix in shortly
